mongodb: #We are using mongodb, please set up a mongodb database and specify the credentials here
  database: "yourDBName"
  port: 27017
  host: "yourHostIp"
  username: "yourUsername"
  password: "yourPassword"


ban-screen:
  - '&4&lBan'
  - '&a'
  - '&cIt looks like you have committed an offence'
  - '&cagainst our rules. You have been punished!'
  - '&e'
  - '&cReason: %reason%'
  - '&cStaff: %staff%'
  - '&cRemaining: %remaining%'
  - '&cPunish ID: %punishId%'
  - '&b'
  - '&c&nYou appeal at yourdiscord.link'

mute-screen: "\n&7You have been muted. &c(%remaining% left)\n"

punish-announcement: "&c%player%"

reasons:
  1:
    type: 'ban' #Available types: "ban", "mute"
    display-name: 'Cheating'
    duration:
      1: '30D'
      2: '60D'
      3: 'Permanently'

